"""
BRFSS Statistical Learning Dashboard
Displays real computed outputs from the analysis pipeline.
All charts are generated by the Python scripts — not synthetic data.
"""
import streamlit as st
import pandas as pd
import os
from PIL import Image

st.set_page_config(
    page_title="BRFSS Statistical Learning",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

NAVY  = "#0D2B5E"
GOLD  = "#C6A84B"
LIGHT = "#F4F6FA"
WHITE = "#FFFFFF"
GREEN = "#2ECC71"
RED   = "#E74C3C"

st.markdown(f"""
<style>
    .stApp {{ background-color: {LIGHT}; }}
    section[data-testid="stSidebar"] {{ background-color: {NAVY}; }}
    section[data-testid="stSidebar"] * {{ color: {WHITE} !important; }}
    section[data-testid="stSidebar"] .stSelectbox label {{ color: {GOLD} !important; font-weight:700; }}
    section[data-testid="stSidebar"] .stSelectbox div[data-baseweb="select"] > div {{
        background-color: rgba(255,255,255,0.15) !important;
        border-color: rgba(255,255,255,0.3) !important;
    }}
    section[data-testid="stSidebar"] .stSelectbox span {{ color: {WHITE} !important; }}
    section[data-testid="stSidebar"] .stSelectbox svg {{ fill: {WHITE} !important; }}
    h1, h2, h3 {{ color: {NAVY}; }}
    .kpi-card {{
        background: {WHITE};
        border-left: 5px solid {GOLD};
        border-radius: 8px;
        padding: 16px 20px;
        box-shadow: 0 2px 8px rgba(13,43,94,0.08);
        margin-bottom: 10px;
    }}
    .kpi-card .label {{ font-size:12px; color:#666; font-weight:700;
        text-transform:uppercase; letter-spacing:0.5px; }}
    .kpi-card .value {{ font-size:26px; font-weight:900; color:{NAVY}; margin-top:4px; }}
    .kpi-card .sub {{ font-size:12px; color:#888; margin-top:3px; }}
    .section-hdr {{
        background: {NAVY}; color:{WHITE}; padding:10px 18px;
        border-radius:6px; font-size:14px; font-weight:700;
        margin-bottom:14px; letter-spacing:0.3px;
    }}
    .finding-box {{
        background:{WHITE}; border-left:6px solid {NAVY};
        border-radius:0 8px 8px 0; padding:16px 20px;
        margin:12px 0; box-shadow:0 2px 6px rgba(13,43,94,0.07);
    }}
    .finding-box .ftitle {{ font-size:11px; font-weight:800; color:{GOLD};
        text-transform:uppercase; letter-spacing:1px; margin-bottom:6px; }}
    .finding-box .fwinner {{ font-size:20px; font-weight:900; color:{NAVY}; margin:4px 0; }}
    .finding-box .fmetric {{ font-size:12px; color:#555; margin-top:3px; }}
    .finding-box .fbody {{ font-size:13px; color:#333; line-height:1.65; margin-top:8px; }}
    .implication {{
        background:#FFF8E7; border:1px solid {GOLD};
        border-radius:8px; padding:14px 18px; margin:10px 0;
    }}
    .implication .ititle {{ font-size:12px; font-weight:800; color:{NAVY};
        text-transform:uppercase; letter-spacing:0.5px; margin-bottom:6px; }}
    .implication .ibody {{ font-size:13px; color:#444; line-height:1.65; }}
    .insight-card {{
        background: linear-gradient(135deg, {NAVY} 0%, #1a3f7a 100%);
        border-radius:10px; padding:18px 22px; margin-bottom:12px;
        box-shadow:0 3px 10px rgba(13,43,94,0.18);
    }}
    .insight-card .ic-tag {{ font-size:11px; font-weight:800; color:{GOLD};
        text-transform:uppercase; letter-spacing:1px; margin-bottom:6px; }}
    .insight-card .ic-title {{ font-size:15px; font-weight:800; color:{WHITE}; margin-bottom:8px; }}
    .insight-card .ic-body {{ font-size:13px; color:rgba(255,255,255,0.85); line-height:1.6; }}
    .insight-card .ic-stat {{ display:inline-block; background:{GOLD}; color:{NAVY};
        font-weight:900; font-size:12px; padding:3px 10px;
        border-radius:20px; margin-top:10px; }}
</style>
""", unsafe_allow_html=True)

# ── Image base path ──────────────────────────────────────────────────────────
BASE = os.path.dirname(os.path.abspath(__file__))

def img(path, caption=None, width=None):
    full = os.path.join(BASE, path)
    if os.path.exists(full):
        st.image(full, caption=caption, use_column_width=(width is None))
    else:
        st.warning(f"Chart not found: {path} — run the pipeline scripts to generate outputs.")

def section(title):
    st.markdown(f'<div class="section-hdr">{title}</div>', unsafe_allow_html=True)

def kpi(label, value, sub=""):
    return f"""<div class="kpi-card">
        <div class="label">{label}</div>
        <div class="value">{value}</div>
        <div class="sub">{sub}</div>
    </div>"""

def finding(tag, winner, metric, body):
    st.markdown(f"""<div class="finding-box">
        <div class="ftitle">🏆 {tag}</div>
        <div class="fwinner">{winner}</div>
        <div class="fmetric">{metric}</div>
        <div class="fbody">{body}</div>
    </div>""", unsafe_allow_html=True)

def implication(title, body):
    st.markdown(f"""<div class="implication">
        <div class="ititle">{title}</div>
        <div class="ibody">{body}</div>
    </div>""", unsafe_allow_html=True)

def insight_card(tag, title, body, stat):
    st.markdown(f"""<div class="insight-card">
        <div class="ic-tag">{tag}</div>
        <div class="ic-title">{title}</div>
        <div class="ic-body">{body}</div>
        <div class="ic-stat">{stat}</div>
    </div>""", unsafe_allow_html=True)

# ── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown(f"""
    <div style='text-align:center; padding:16px 0 8px 0;'>
        <div style='font-size:30px;'>📊</div>
        <div style='font-size:16px; font-weight:800; color:{GOLD}; margin-top:4px;'>BRFSS Analysis</div>
        <div style='font-size:11px; color:#aaa; margin-top:3px;'>Statistical Learning · 2011–2024</div>
    </div>
    <hr style='border-color:rgba(255,255,255,0.15); margin:8px 0 16px 0;'>
    """, unsafe_allow_html=True)

    page = st.selectbox("Navigate", [
        "🏠  Overview",
        "🔍  Exploratory Data Analysis",
        "📈  Regression Models",
        "🎯  Classification",
        "🔵  Clustering & PCA",
        "📋  Findings & Conclusions",
    ])

    st.markdown(f"""
    <hr style='border-color:rgba(255,255,255,0.15); margin:16px 0;'>
    <div style='font-size:11px; color:#aaa; line-height:1.8;'>
        <b style='color:{GOLD};'>Dataset</b><br>
        CDC BRFSS 2011–2024<br>
        55 U.S. locations<br>
        110,880 raw rows<br>
        Population-level %<br><br>
        <b style='color:{GOLD};'>Methods</b><br>
        OLS · Ridge Regression<br>
        Logistic · Decision Tree<br>
        Random Forest · SVM<br>
        K-Means · PCA<br><br>
        <b style='color:{GOLD};'>Author</b><br>
        Chris Rodrigues<br>
        Illinois Tech · MAS DS
    </div>
    """, unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE: OVERVIEW
# ════════════════════════════════════════════════════════════════════════════
if "Overview" in page:
    st.markdown(f"""
    <h1 style='margin-bottom:4px;'>BRFSS Statistical Learning Analysis</h1>
    <p style='color:#555; font-size:15px; margin-top:0;'>
        Can national physical activity levels and dietary habits predict obesity rates
        across U.S. demographic groups from 2011 to 2024?
    </p>
    """, unsafe_allow_html=True)

    c1,c2,c3,c4,c5,c6 = st.columns(6)
    with c1: st.markdown(kpi("Raw Rows", "110,880", "before cleaning"), unsafe_allow_html=True)
    with c2: st.markdown(kpi("Years", "2011–2024", "14 annual cycles"), unsafe_allow_html=True)
    with c3: st.markdown(kpi("Locations", "55", "states & territories"), unsafe_allow_html=True)
    with c4: st.markdown(kpi("Best Reg. R²", "0.237", "Ridge combined"), unsafe_allow_html=True)
    with c5: st.markdown(kpi("Best CV Acc.", "70.3%", "Random Forest, Dataset B"), unsafe_allow_html=True)
    with c6: st.markdown(kpi("Clusters", "k = 4", "silhouette = 0.43"), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    section("Study Design")
    col1, col2 = st.columns([3, 2])
    with col1:
        st.markdown(f"""
        <div style='background:{WHITE}; border-radius:10px; padding:22px;
                    box-shadow:0 2px 8px rgba(13,43,94,0.08);'>
            <div style='font-size:14px; color:#333; line-height:1.8;'>
                <b style='color:{NAVY};'>Unit of analysis:</b> Every value is a population-level
                percentage — the proportion of adults in a given state, year, and demographic group
                who meet a criterion. This is an <b>ecological analysis</b>, not individual-level data.<br><br>
                <b style='color:{NAVY};'>Three behavioral classes:</b><br>
                &nbsp;&nbsp;• <b>Obesity</b> — % adults with obesity (2011–2024)<br>
                &nbsp;&nbsp;• <b>Inactive</b> — % adults with no leisure-time physical activity (2011–2024)<br>
                &nbsp;&nbsp;• <b>PoorDiet</b> — avg of % eating fruit &lt;1/day and veg &lt;1/day (2017, 2019, 2021 only)<br><br>
                <b style='color:{NAVY};'>Stratification:</b> Each location × year is broken down by
                Age, Sex, Income, Education, Race/Ethnicity, and Total — giving 391 national
                observations for activity and 84 for diet (limited diet survey years).
            </div>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        section("Pipeline")
        st.markdown(f"""
        <div style='background:{WHITE}; border-radius:10px; padding:18px;
                    box-shadow:0 2px 8px rgba(13,43,94,0.08); font-size:13px;
                    color:#333; line-height:2;'>
            <b style='color:{GOLD};'>1.</b> brfss_clean.py &nbsp;→&nbsp; ETL pipeline<br>
            <b style='color:{GOLD};'>2.</b> brfss_eda.py &nbsp;&nbsp;&nbsp;→&nbsp; EDA & correlations<br>
            <b style='color:{GOLD};'>3.</b> brfss_model.py &nbsp;→&nbsp; OLS + Ridge regression<br>
            <b style='color:{GOLD};'>4.</b> brfss_classify.py → Classification<br>
            <b style='color:{GOLD};'>5.</b> brfss_cluster.py → K-Means + PCA<br>
            <b style='color:{GOLD};'>6.</b> app.py &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;→&nbsp; This dashboard
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    section("Model Results Summary")
    results = pd.DataFrame({
        "Model": ["OLS: Obesity ~ Inactive", "OLS: Obesity ~ PoorDiet",
                  "Ridge: Obesity ~ Inactive + PoorDiet",
                  "Classification (Dataset A) — Best CV",
                  "Classification (Dataset B) — Best CV",
                  "K-Means Clustering"],
        "n": [391, 84, 84, 391, 84, 391],
        "Result": ["R²=0.213", "R²=0.170", "R²=0.237, CV R²=0.161",
                   "Random Forest 67.8% CV accuracy",
                   "Random Forest 70.3% CV accuracy",
                   "k=4, silhouette=0.43"],
        "Key Finding": [
            "β=0.445, p<0.001 — inactivity significantly predicts obesity",
            "β=0.658, p<0.001 — diet has larger per-unit effect",
            "Combined model outperforms single-predictor OLS",
            "Inactive + StratCat predicts high/low obesity risk",
            "Adding PoorDiet improves classification performance",
            "4 clusters incl. Young Adult Paradox"
        ]
    })
    st.dataframe(results, use_container_width=True, hide_index=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE: EDA
# ════════════════════════════════════════════════════════════════════════════
elif "EDA" in page:
    st.markdown("<h1>Exploratory Data Analysis</h1>", unsafe_allow_html=True)
    st.markdown("*Distributions, trends, demographic breakdowns, and cross-indicator correlations.*")

    tab1, tab2, tab3, tab4 = st.tabs(["🏋️ Obesity", "🚶 Physical Activity", "🥦 Diet", "🔗 Combined"])

    with tab1:
        section("Obesity — Distribution & National Trend")
        c1, c2 = st.columns(2)
        with c1: img("eda_outputs/obesity_q1_distribution.png", "Distribution of obesity rates across all strata")
        with c2: img("eda_outputs/obesity_q2_trend.png", "National obesity trend 2011–2024")

        section("Obesity by Demographic Group")
        c1, c2, c3 = st.columns(3)
        with c1: img("eda_outputs/obesity_q3_age_(years).png", "By Age")
        with c2: img("eda_outputs/obesity_q3_education.png", "By Education")
        with c3: img("eda_outputs/obesity_q3_income.png", "By Income")
        c4, c5 = st.columns(2)
        with c4: img("eda_outputs/obesity_q3_race_ethnicity.png", "By Race/Ethnicity")
        with c5: img("eda_outputs/obesity_q3_sex.png", "By Sex")

        finding(
            "Obesity EDA Finding",
            "Obesity rose +5.8 pp nationally (2011–2024)",
            "Correlation with Year: r = +0.98",
            "The national obesity trend is nearly perfectly linear with time — a stronger "
            "statistical relationship than with any behavioral indicator. Education and income "
            "show the steepest demographic gradients: college graduates have substantially lower "
            "obesity than adults without a high school diploma. This socioeconomic gap widened over the study period."
        )

        img("eda_outputs/obesity_q4_variation_by_strat.png", "Obesity variation by stratification category")

    with tab2:
        section("Physical Activity — Distribution & National Trend")
        c1, c2 = st.columns(2)
        with c1: img("eda_outputs/activity_q1_distribution.png", "Distribution of inactivity rates")
        with c2: img("eda_outputs/activity_q2_trend.png", "National inactivity trend 2011–2024")

        section("Inactivity by Demographic Group")
        c1, c2, c3 = st.columns(3)
        with c1: img("eda_outputs/activity_q3_age_(years).png", "By Age")
        with c2: img("eda_outputs/activity_q3_education.png", "By Education")
        with c3: img("eda_outputs/activity_q3_income.png", "By Income")
        c4, c5 = st.columns(2)
        with c4: img("eda_outputs/activity_q3_race_ethnicity.png", "By Race/Ethnicity")
        with c5: img("eda_outputs/activity_q3_sex.png", "By Sex")

        finding(
            "Activity EDA Finding",
            "Inactivity showed NO significant trend 2011–2024",
            "Correlation with Year: r = −0.39, p = 0.17",
            "While obesity rose steadily, physical inactivity remained flat — the two indicators "
            "diverged over the study period. This is a critical finding: the rising obesity trend "
            "cannot be explained by worsening physical activity rates alone. Education shows the "
            "strongest inactivity-obesity correlation (r = +0.78)."
        )

        img("eda_outputs/activity_q4_vs_obesity.png", "Inactivity vs Obesity scatter by demographic group")

    with tab3:
        section("Diet — Fruit & Vegetable Consumption")
        st.info("⚠️ Diet data available for 2017, 2019, and 2021 only (Overall stratification). All diet findings are based on 84 observations across 3 years.")
        img("eda_outputs/diet_q1_rates.png", "Low fruit and low vegetable consumption rates")

        section("Diet by Demographic Group")
        c1, c2, c3 = st.columns(3)
        with c1: img("eda_outputs/diet_q2_age_(years).png", "By Age")
        with c2: img("eda_outputs/diet_q2_education.png", "By Education")
        with c3: img("eda_outputs/diet_q2_income.png", "By Income")
        c4, c5 = st.columns(2)
        with c4: img("eda_outputs/diet_q2_race_ethnicity.png", "By Race/Ethnicity")
        with c5: img("eda_outputs/diet_q2_sex.png", "By Sex")

        img("eda_outputs/diet_q3_vs_obesity.png", "PoorDiet vs Obesity scatter")

        finding(
            "Diet EDA Finding",
            "PoorDiet has a larger per-unit effect than Inactivity",
            "β = 0.658 vs β = 0.445 (regression)",
            "Despite having only 3 years of data, diet quality shows a stronger per-unit "
            "relationship with obesity than physical activity. Low-income and less-educated "
            "groups show both higher inactivity AND poorer diet — compounding risk. "
            "The limited diet data (84 rows) means these findings should be interpreted cautiously."
        )

    with tab4:
        section("Cross-Indicator Correlations")
        img("eda_outputs/combined_q1_correlation.png", "Correlation matrix: Obesity, Inactive, PoorDiet")
        c1, c2 = st.columns(2)
        with c1: img("eda_outputs/combined_q2_vif.png", "Variance Inflation Factor — multicollinearity check")
        with c2: img("eda_outputs/combined_scatter_matrix.png", "Scatter matrix across all three indicators")

        finding(
            "Multicollinearity Finding",
            "VIF = 28.15 between Inactive and PoorDiet",
            "Justifies Ridge regression for the combined model",
            "Inactive and PoorDiet are highly correlated with each other (VIF=28.15), meaning "
            "OLS coefficient estimates would be unreliable in a combined model. This is why "
            "Ridge regression was selected for Model 3 — L2 regularization stabilizes "
            "coefficient estimates under multicollinearity."
        )

# ════════════════════════════════════════════════════════════════════════════
# PAGE: REGRESSION
# ════════════════════════════════════════════════════════════════════════════
elif "Regression" in page:
    st.markdown("<h1>Regression Models</h1>", unsafe_allow_html=True)
    st.markdown("*Three models predicting obesity rates from behavioral indicators.*")

    tab1, tab2, tab3 = st.tabs(["Model 1 — Inactive", "Model 2 — PoorDiet", "Model 3 — Ridge Combined"])

    with tab1:
        section("Model 1: Obesity ~ Physical Inactivity (OLS)")
        st.markdown("**n = 391 &nbsp;|&nbsp; All stratification groups &nbsp;|&nbsp; 2011–2024**")
        col1, col2 = st.columns([3, 1])
        with col1:
            img("model_outputs/model1_inactive.png", "Obesity vs Inactivity with OLS fit line")
        with col2:
            st.markdown(kpi("R²", "0.213", ""), unsafe_allow_html=True)
            st.markdown(kpi("β (Inactive)", "0.445", "p < 0.001 ***"), unsafe_allow_html=True)
            st.markdown(kpi("n", "391", "all strata, 14 years"), unsafe_allow_html=True)
        img("model_outputs/residuals_model_1_obesitybyinactive.png", "Residual diagnostics — Fitted vs Residuals and Q-Q Plot")
        finding(
            "Model 1 Finding",
            "Inactivity significantly predicts obesity",
            "β = 0.445 · R² = 0.213 · p < 0.001 · n = 391",
            "For every 1 percentage point increase in inactivity, obesity rises by 0.445 points. "
            "The relationship is statistically robust across all demographic groups and 14 years. "
            "However, inactivity alone explains only 21.3% of obesity variance — the majority of "
            "variation is driven by factors outside this model. Education groups show the strongest "
            "inactivity-obesity correlation (r = +0.78)."
        )
        implication("⚠️ Ecological Caution",
            "This is a population-level correlation — it does not mean inactive individuals are "
            "more likely to be obese. The ecological fallacy means group-level findings cannot "
            "be applied to individuals without individual-level confirmation.")

    with tab2:
        section("Model 2: Obesity ~ PoorDiet (OLS)")
        st.markdown("**n = 84 &nbsp;|&nbsp; All stratification groups &nbsp;|&nbsp; 2017, 2019, 2021 only**")
        col1, col2 = st.columns([3, 1])
        with col1:
            img("model_outputs/model2_diet.png", "Obesity vs PoorDiet with OLS fit line")
        with col2:
            st.markdown(kpi("R²", "0.170", ""), unsafe_allow_html=True)
            st.markdown(kpi("β (PoorDiet)", "0.658", "p < 0.001 ***"), unsafe_allow_html=True)
            st.markdown(kpi("n", "84", "3 diet years only"), unsafe_allow_html=True)
        img("model_outputs/residuals_model_2_obesitybypoordiet.png", "Residual diagnostics")
        finding(
            "Model 2 Finding",
            "PoorDiet has a larger per-unit effect than Inactivity",
            "β = 0.658 · R² = 0.170 · p < 0.001 · n = 84",
            "Each 1 point worsening in PoorDiet score is associated with a 0.658 point rise in "
            "obesity — a larger coefficient than inactivity (0.445). Despite having only 84 rows "
            "across 3 years, the relationship is statistically significant. The lower R² (0.170 vs "
            "0.213) compared to Model 1 is partly attributable to the smaller, less diverse sample."
        )

    with tab3:
        section("Model 3: Obesity ~ Inactive + PoorDiet (Ridge Regression)")
        st.markdown("**n = 84 &nbsp;|&nbsp; Ridge used due to VIF = 28.15 between predictors &nbsp;|&nbsp; α selected via 5-fold CV**")
        col1, col2 = st.columns(2)
        with col1:
            img("model_outputs/model3_ridge_coefficients.png", "Standardized Ridge coefficients")
        with col2:
            img("model_outputs/model3_predicted_vs_actual.png", "Predicted vs Actual obesity rates")
        c1,c2,c3 = st.columns(3)
        with c1: st.markdown(kpi("R² (train)", "0.237", "Combined model"), unsafe_allow_html=True)
        with c2: st.markdown(kpi("CV R²", "0.161", "5-fold cross-validated"), unsafe_allow_html=True)
        with c3: st.markdown(kpi("VIF", "28.15", "Justifies Ridge over OLS"), unsafe_allow_html=True)
        finding(
            "Model 3 Finding",
            "Ridge combined model achieves R² = 0.237",
            "Train R² = 0.237 · CV R² = 0.161 · n = 84",
            "The combined model outperforms both single-predictor models. PoorDiet receives "
            "a higher standardized coefficient than Inactive under Ridge — consistent with its "
            "larger raw β. The gap between train R² (0.237) and CV R² (0.161) reflects the "
            "limited sample size (84 rows). Together, both behavioral indicators explain only "
            "~24% of obesity variation — the remaining 76% is driven by unmeasured factors."
        )
        implication("💡 Why Ridge?",
            "OLS is unreliable when predictors are highly correlated (VIF=28.15). "
            "Ridge regression adds an L2 penalty that stabilizes coefficient estimates "
            "without zeroing out features — appropriate here since both Inactive and "
            "PoorDiet carry genuine signal.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE: CLASSIFICATION
# ════════════════════════════════════════════════════════════════════════════
elif "Classification" in page:
    st.markdown("<h1>Classification — Predicting High vs Low Obesity Risk</h1>", unsafe_allow_html=True)
    st.markdown("*Binary outcome: High risk (Obesity > median) vs Low risk (Obesity ≤ median)*")

    tab1, tab2 = st.tabs(["Dataset A — Inactive + StratCat", "Dataset B — Inactive + PoorDiet + StratCat"])

    for tab, prefix, n_rows, label in [
        (tab1, "Dataset_A_Inactive_and_StratCat1", "391", "Dataset A: Inactive + StratificationCategory1"),
        (tab2, "Dataset_B_Inactive_and_PoorDiet_and_StratCat1", "84", "Dataset B: Inactive + PoorDiet + StratificationCategory1"),
    ]:
        with tab:
            section(f"Cross-Validation Results — {label}")
            results_file = f"classify_outputs/{prefix}_results.csv"
            if os.path.exists(os.path.join(BASE, results_file)):
                df = pd.read_csv(os.path.join(BASE, results_file))
                df_show = df[["Classifier","CV_Accuracy","CV_Acc_Std","CV_F1","CV_AUC"]].copy()
                df_show.columns = ["Classifier","CV Accuracy","CV Acc Std","CV F1","CV AUC"]
                df_show["CV Accuracy"] = (df_show["CV Accuracy"]*100).round(1).astype(str) + "%"
                df_show["CV Acc Std"] = ("±" + (df_show["CV Acc Std"]*100).round(1).astype(str) + "%")
                df_show["CV F1"] = df_show["CV F1"].round(3)
                df_show["CV AUC"] = df_show["CV AUC"].round(3)
                st.dataframe(df_show, use_container_width=True, hide_index=True)

            col1, col2 = st.columns(2)
            with col1:
                img(f"classify_outputs/{prefix}_cv_comparison.png", "CV accuracy comparison across classifiers")
                img(f"classify_outputs/{prefix}_roc_curves.png", "ROC curves")
            with col2:
                img(f"classify_outputs/{prefix}_confusion_matrices.png", "Confusion matrices")
                img(f"classify_outputs/{prefix}_feature_importance.png", "Random Forest feature importance")

            img(f"classify_outputs/{prefix}_decision_tree.png", "Decision Tree structure")

    finding(
        "Classification Finding",
        "Dataset B (with PoorDiet) outperforms Dataset A",
        "Dataset A best CV: Random Forest 67.8% · Dataset B best CV: Random Forest 70.3%",
        "Adding PoorDiet to the feature set improves all classifiers — confirming diet quality "
        "adds independent predictive signal beyond inactivity alone. Across both datasets, "
        "classifiers achieve 65–70% CV accuracy, which is meaningful but modest — consistent "
        "with the regression finding that behavioral indicators explain only ~24% of obesity "
        "variation. Random Forest is the top performer in both datasets."
    )
    implication("⚠️ Note on Random Forest Train Accuracy",
        "Random Forest achieves 100% training accuracy in both datasets — this is expected "
        "overfitting from an unconstrained ensemble on small samples. CV accuracy (67–70%) "
        "is the correct measure of generalizability.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE: CLUSTERING
# ════════════════════════════════════════════════════════════════════════════
elif "Clustering" in page:
    st.markdown("<h1>K-Means Clustering & PCA</h1>", unsafe_allow_html=True)
    st.markdown("*Unsupervised discovery of behavioral phenotypes across U.S. demographic groups.*")

    section("Optimal K Selection")
    img("cluster_outputs/cluster_1_optimal_k.png", "Elbow method and silhouette scores — k=4 selected")

    section("PCA Cluster Visualization")
    img("cluster_outputs/cluster_2_pca.png", "Clusters projected onto 2 principal components")

    section("Cluster Profiles")
    col1, col2 = st.columns([2, 1])
    with col1:
        img("cluster_outputs/cluster_3_profiles.png", "Mean feature values per cluster")
    with col2:
        if os.path.exists(os.path.join(BASE, "cluster_outputs/cluster_profiles.csv")):
            df = pd.read_csv(os.path.join(BASE, "cluster_outputs/cluster_profiles.csv"))
            df.columns = ["Cluster", "Obesity %", "Inactive %", "PoorDiet %"]
            df["Cluster"] = df["Cluster"].map({
                0: "🔴 High Risk",
                1: "🟢 Low Risk",
                2: "🟡 Moderate",
                3: "🔵 Young Adult Paradox"
            })
            st.dataframe(df, use_container_width=True, hide_index=True)
            st.markdown(f"""
            <div class="kpi-card" style="margin-top:10px;">
                <div class="label">Silhouette Score</div>
                <div class="value">0.43</div>
                <div class="sub">Moderate — clusters are real but gradual</div>
            </div>""", unsafe_allow_html=True)

    section("Cluster Composition by Demographic Group")
    col1, col2 = st.columns(2)
    with col1:
        img("cluster_outputs/cluster_4_crosstab.png", "Which demographic groups fall in each cluster?")
    with col2:
        img("cluster_outputs/cluster_5_composition.png", "Cluster composition breakdown")

    finding(
        "Clustering Finding",
        "4 Behavioral Phenotypes — Including the Young Adult Paradox",
        "k=4 · Silhouette = 0.43 · Clusters cut across demographic boundaries",
        "The Young Adult Paradox cluster (Cluster 3) has low obesity (14.9%) despite high PoorDiet "
        "(31.2%) and moderate inactivity (19%). The unsupervised algorithm independently confirmed "
        "what EDA first observed — young adults' metabolic profile buffers the impact of poor behavioral "
        "choices on weight. Education and income groups drive the extreme clusters (High Risk and Low Risk). "
        "No single demographic category falls entirely into one cluster — risk profiles are not "
        "determined by demographics alone."
    )
    implication("💡 Why This Matters for Public Health",
        "A one-size-fits-all intervention strategy fails because it targets four distinct populations. "
        "The High Risk cluster needs structural support (food access, safe recreation spaces). "
        "The Young Adult Paradox cluster needs preventive dietary intervention NOW — before "
        "metabolic buffering diminishes with age. Cluster membership is socioeconomic, not demographic.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE: FINDINGS & CONCLUSIONS
# ════════════════════════════════════════════════════════════════════════════
elif "Findings" in page:
    st.markdown("<h1>Findings & Conclusions</h1>", unsafe_allow_html=True)
    st.markdown("*Complete summary of all results, insights, and public health implications.*")

    c1,c2,c3,c4,c5 = st.columns(5)
    with c1: st.markdown(kpi("Best Reg. R²", "0.237", "Ridge — Inactive + PoorDiet"), unsafe_allow_html=True)
    with c2: st.markdown(kpi("Inactivity β", "0.445", "p < 0.001, n=391"), unsafe_allow_html=True)
    with c3: st.markdown(kpi("PoorDiet β", "0.658", "p < 0.001, n=84"), unsafe_allow_html=True)
    with c4: st.markdown(kpi("Best CV Acc.", "70.3%", "Random Forest, Dataset B"), unsafe_allow_html=True)
    with c5: st.markdown(kpi("Clusters", "k=4", "silhouette=0.43"), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    section("Key Findings Across All Analyses")

    col1, col2 = st.columns(2)
    with col1:
        insight_card("Regression — Model 1",
            "Inactivity significantly predicts obesity — but only partially",
            "β=0.445, R²=0.213, p<0.001, n=391. For every 1pp rise in inactivity, "
            "obesity rises 0.445pp. Robust across all demographic groups and 14 years. "
            "But inactivity explains only 21% of variance.",
            "R² = 0.213 · β = 0.445")
        insight_card("Regression — Model 3",
            "Combined behavioral model explains ~24% of obesity variation",
            "Ridge R²=0.237, CV R²=0.161. Both indicators together outperform either alone. "
            "The 76% unexplained variance points to unmeasured structural factors: "
            "food environment, ultra-processed foods, chronic stress, sleep.",
            "R² = 0.237 · CV R² = 0.161")
        insight_card("Clustering",
            "Young Adult Paradox: Low obesity despite poor diet",
            "K-Means (k=4) independently confirmed the EDA observation that young adults "
            "have poor dietary habits yet low obesity — metabolic buffering masks deteriorating "
            "behavioral trajectories that will emerge as they age.",
            "Cluster 3: Obesity 14.9% · PoorDiet 31.2%")

    with col2:
        insight_card("Temporal Trend",
            "Obesity rose +5.8pp while inactivity was flat",
            "Obesity: r=+0.98 with Year. Inactivity: r=−0.39, p=0.17 — not significant. "
            "The behavioral indicators explain cross-sectional demographic variation "
            "far better than the national temporal trend. Something else is driving rising obesity.",
            "Obesity r=+0.98 · Inactivity p=0.17 (n.s.)")
        insight_card("Classification",
            "Behavioral data achieves 65–70% accuracy — meaningful but modest",
            "Dataset B (with PoorDiet) outperforms Dataset A. Random Forest is the best "
            "classifier in both. 100% train accuracy reflects overfitting — CV accuracy "
            "is the honest measure. Consistent with R²≈0.24 from regression.",
            "Dataset B: 70.3% CV Accuracy")
        insight_card("Socioeconomic Gradient",
            "Education & income are the dominant structural factors",
            "Education shows the strongest inactivity-obesity correlation (r=+0.78). "
            "Education and income groups concentrate in the extreme clusters. "
            "Behavioral indicators are partly proxies for structural inequality — "
            "not just independent causes of obesity.",
            "Education r = +0.78 with obesity")

    st.markdown("<br>", unsafe_allow_html=True)
    section("Public Health Implications")

    col3, col4 = st.columns(2)
    with col3:
        implication("🏥 Behavioral interventions alone are insufficient",
            "Behavioral indicators explain only ~24% of obesity variation and inactivity is not "
            "rising while obesity is. Campaigns focused solely on individual behavior change will "
            "have limited impact. Structural factors — the food environment, built environment, "
            "income inequality — require policy attention alongside behavior change.")
        implication("🎯 Target socioeconomic gradients, not demographic labels",
            "The strongest risk signal comes from education and income, not from age, sex, or "
            "race/ethnicity per se. Interventions improving access to healthy food and safe "
            "recreational spaces for low-income communities address the root cause.")
    with col4:
        implication("👨‍🎓 Young adults need preventive attention NOW",
            "The Young Adult Paradox shows that current obesity rates in young adults mask "
            "deteriorating behavioral trajectories. Intervene before metabolic buffering "
            "diminishes with age — not after obesity is already observable.")
        implication("📊 Collect more diet data",
            "Diet shows a larger per-unit effect (β=0.658) than inactivity (β=0.445) but is "
            "only available for 3 years. Expanding annual dietary collection would substantially "
            "improve the evidence base and enable more robust modeling.")

    section("Study Limitations")
    lims = [
        ("Ecological Fallacy", "All analysis uses population averages — findings cannot be applied to individuals."),
        ("Diet data: 3 years only", "PoorDiet is available for 2017, 2019, 2021 only — 84 rows total. Limited statistical power."),
        ("Crude activity measure", "Inactive captures only absence of leisure-time activity — not occupational or transport activity."),
        ("PoorDiet imputation", "79% of PoorDiet values in clustering are imputed using stratification group means."),
        ("Self-reported data", "BMI from self-reported height/weight underestimates actual obesity prevalence."),
        ("Cross-sectional surveys", "Different individuals are surveyed each year — no individual longitudinal tracking."),
    ]
    c1, c2 = st.columns(2)
    for i, (title, desc) in enumerate(lims):
        col = c1 if i % 2 == 0 else c2
        with col:
            st.markdown(f"""
            <div style='background:{WHITE}; border-radius:8px; padding:12px 16px;
                        border-left:4px solid {RED if i < 2 else GOLD};
                        margin-bottom:10px; box-shadow:0 1px 4px rgba(0,0,0,0.05);'>
                <div style='font-size:12px; font-weight:800; color:{NAVY}; margin-bottom:3px;'>⚠️ {title}</div>
                <div style='font-size:13px; color:#555; line-height:1.5;'>{desc}</div>
            </div>""", unsafe_allow_html=True)

    st.markdown(f"""
    <div style='text-align:center; margin-top:30px; padding:16px;
                border-top:2px solid {GOLD}; color:#888; font-size:13px;'>
        Illinois Institute of Technology · MAS Data Science · Statistical Learning · Chris Rodrigues · 2025<br>
        <a href='https://github.com/chrisharry99us/brfss-statistical-learning'
           style='color:{GOLD}; text-decoration:none;'>
            📂 github.com/chrisharry99us/brfss-statistical-learning
        </a>
    </div>
    """, unsafe_allow_html=True)
