"""
BRFSS Statistical Learning Dashboard
Displays real computed outputs from the analysis pipeline.
All charts are generated by the Python scripts — not synthetic data.
"""
import streamlit as st
import pandas as pd
import os
from PIL import Image

st.set_page_config(
    page_title="BRFSS Statistical Learning",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Design Tokens ────────────────────────────────────────────────────────────
NAVY    = "#0F2D6F"   # primary navy
GOLD    = "#C8992B"   # warm gold accent
BG      = "#F7F8FC"   # app background
SURFACE = "#FFFFFF"   # card surface
BORDER  = "#E2E6F0"   # card border
TEXT    = "#111827"   # primary text
SLATE   = "#4B5563"   # secondary text
MUTED   = "#9CA3AF"   # tertiary / labels
WHITE   = "#FFFFFF"
# Legacy aliases kept for inline references in page content
LIGHT   = BG
GREEN   = "#059669"
RED     = "#DC2626"

st.markdown(f"""
<style>
/* ═══════════════════════════════════════════════════════════════════
   BRFSS DASHBOARD — PREMIUM ANALYTICS DESIGN SYSTEM
   ═══════════════════════════════════════════════════════════════════ */

/* ── Base ── */
.stApp {{ background: {BG}; font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; }}
.block-container {{ padding-top: 28px; padding-bottom: 48px; max-width: 1200px; }}
#MainMenu, footer {{ visibility: hidden; }}

/* ── Sidebar ── */
section[data-testid="stSidebar"] {{
    background: #0A2558;
    border-right: 1px solid rgba(255,255,255,0.06);
}}
section[data-testid="stSidebar"] * {{ color: {WHITE} !important; }}
section[data-testid="stSidebar"] .stSelectbox label {{
    color: {GOLD} !important; font-size: 10px !important;
    font-weight: 700 !important; text-transform: uppercase; letter-spacing: 1px;
}}
section[data-testid="stSidebar"] .stSelectbox div[data-baseweb="select"] > div {{
    background: rgba(255,255,255,0.1) !important;
    border: 1px solid rgba(255,255,255,0.18) !important;
    border-radius: 8px !important;
}}
section[data-testid="stSidebar"] .stSelectbox span {{ color: {WHITE} !important; }}
section[data-testid="stSidebar"] .stSelectbox svg {{ fill: {WHITE} !important; }}

/* ── Typography ── */
h1 {{ color: {TEXT}; font-size: 30px; font-weight: 800; letter-spacing: -0.6px; }}
h2 {{ color: {TEXT}; font-size: 20px; font-weight: 700; letter-spacing: -0.3px; }}
h3 {{ color: {TEXT}; font-size: 16px; font-weight: 600; }}

/* ── Page Hero ── */
.page-hero {{
    padding: 6px 0 26px 0;
    border-bottom: 1px solid {BORDER};
    margin-bottom: 30px;
}}
.page-hero-eye {{
    font-size: 11px; font-weight: 700; color: {GOLD};
    text-transform: uppercase; letter-spacing: 1.2px; margin-bottom: 10px;
}}
.page-hero-title {{
    font-size: 32px; font-weight: 800; color: {TEXT};
    letter-spacing: -0.8px; margin: 0 0 10px 0; line-height: 1.15;
}}
.page-hero-sub {{
    font-size: 15px; color: {SLATE}; margin: 0; line-height: 1.65; max-width: 720px;
}}

/* ── Section Labels (lightweight, replaces heavy navy bars) ── */
.section-label {{
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1.3px;
    color: {MUTED};
    margin: 30px 0 14px 0;
}}
.section-label::after {{
    content: '';
    flex: 1;
    height: 1px;
    background: {BORDER};
}}

/* ── KPI Cards ── */
.kpi-card {{
    background: {SURFACE};
    border: 1px solid {BORDER};
    border-top: 3px solid {GOLD};
    border-radius: 10px;
    padding: 18px 20px 15px 20px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 4px 14px rgba(15,45,111,0.05);
    margin-bottom: 8px;
}}
.kpi-card .label {{
    font-size: 10px; color: {MUTED}; font-weight: 700;
    text-transform: uppercase; letter-spacing: 0.9px;
}}
.kpi-card .value {{
    font-size: 26px; font-weight: 800; color: {TEXT};
    margin-top: 8px; letter-spacing: -0.5px; line-height: 1.15;
}}
.kpi-card .sub {{ font-size: 12px; color: {SLATE}; margin-top: 6px; }}

/* ── Content Card (generic container) ── */
.card {{
    background: {SURFACE};
    border: 1px solid {BORDER};
    border-radius: 12px;
    padding: 22px 26px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 4px 14px rgba(15,45,111,0.05);
    margin-bottom: 14px;
    font-size: 14px;
    color: #374151;
    line-height: 1.8;
}}

/* ── Finding / Result Boxes ── */
.finding-box {{
    background: {SURFACE};
    border: 1px solid {BORDER};
    border-radius: 12px;
    padding: 20px 24px;
    margin: 12px 0;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 4px 14px rgba(15,45,111,0.05);
    position: relative;
    overflow: hidden;
}}
.finding-box::before {{
    content: '';
    position: absolute; top: 0; left: 0; right: 0; height: 3px;
    background: linear-gradient(90deg, {NAVY} 0%, {GOLD} 100%);
}}
.finding-box .ftitle {{
    font-size: 10px; font-weight: 700; color: {MUTED};
    text-transform: uppercase; letter-spacing: 1.1px; margin-bottom: 8px;
}}
.finding-box .fwinner {{
    font-size: 21px; font-weight: 800; color: {TEXT};
    margin: 4px 0; letter-spacing: -0.3px;
}}
.finding-box .fmetric {{
    display: inline-block; font-size: 12px; font-weight: 600; color: {NAVY};
    background: rgba(15,45,111,0.08); padding: 3px 11px; border-radius: 20px; margin-top: 6px;
}}
.finding-box .fbody {{
    font-size: 13.5px; color: {SLATE}; line-height: 1.75; margin-top: 12px;
    border-top: 1px solid #F3F4F6; padding-top: 12px;
}}

/* ── Implication / Amber Note Boxes ── */
.implication {{
    background: #FFFBEB; border: 1px solid #FCD34D;
    border-radius: 10px; padding: 16px 20px; margin: 12px 0;
}}
.implication .ititle {{
    font-size: 11px; font-weight: 700; color: #92400E;
    text-transform: uppercase; letter-spacing: 0.6px; margin-bottom: 6px;
}}
.implication .ibody {{ font-size: 13.5px; color: #78350F; line-height: 1.75; }}

/* ── Insight Cards (dark, for highlights / conclusions) ── */
.insight-card {{
    background: {NAVY};
    border-radius: 12px; padding: 22px 24px; margin-bottom: 12px;
    border: 1px solid rgba(255,255,255,0.07);
}}
.insight-card .ic-tag {{
    font-size: 10px; font-weight: 700; color: {GOLD};
    text-transform: uppercase; letter-spacing: 1.1px; margin-bottom: 8px;
}}
.insight-card .ic-title {{
    font-size: 16px; font-weight: 700; color: {WHITE};
    margin-bottom: 10px; letter-spacing: -0.2px;
}}
.insight-card .ic-body {{ font-size: 13.5px; color: rgba(255,255,255,0.78); line-height: 1.75; }}
.insight-card .ic-stat {{
    display: inline-block;
    background: rgba(200,153,43,0.18); color: {GOLD};
    font-weight: 700; font-size: 13px; padding: 4px 12px;
    border-radius: 20px; margin-top: 12px;
    border: 1px solid rgba(200,153,43,0.35);
}}

/* ── Behavioral Class Cards (Obesity / Activity / Diet) ── */
.class-card {{
    background: {SURFACE}; border: 1px solid {BORDER};
    border-radius: 12px; padding: 24px 18px; text-align: center;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(15,45,111,0.05);
}}
.class-card .cc-icon {{ font-size: 30px; margin-bottom: 12px; }}
.class-card .cc-title {{ font-size: 15px; font-weight: 700; color: {TEXT}; margin-bottom: 8px; }}
.class-card .cc-body {{ font-size: 13px; color: {SLATE}; line-height: 1.75; }}
.class-card .cc-stat {{
    display: inline-block; margin-top: 12px;
    font-size: 12px; font-weight: 700; color: {NAVY};
    background: rgba(15,45,111,0.08);
    padding: 4px 14px; border-radius: 20px;
    border: 1px solid rgba(15,45,111,0.15);
}}

/* ── Ecological Warning ── */
.eco-warning {{
    background: #FFFBEB; border: 1px solid #FCD34D;
    border-radius: 10px; padding: 16px 20px; margin: 16px 0;
    font-size: 14px; color: #78350F; line-height: 1.8;
}}

/* ── Research Question Cards ── */
.rq-card {{
    background: {SURFACE};
    border: 1px solid {BORDER};
    border-left: 4px solid {NAVY};
    border-radius: 0 12px 12px 0;
    padding: 18px 22px;
    margin-bottom: 12px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(15,45,111,0.04);
}}

/* ── Dataframe wrapper ── */
.stDataFrame {{ border-radius: 10px !important; }}
[data-testid="stDataFrame"] > div {{ border-radius: 10px !important; border: 1px solid {BORDER} !important; }}
</style>
""", unsafe_allow_html=True)

# ── Image base path ──────────────────────────────────────────────────────────
BASE = os.path.dirname(os.path.abspath(__file__))

def img(path, caption=None, width=None):
    """Load a real chart PNG from the pipeline outputs folder."""
    full = os.path.join(BASE, path)
    if os.path.exists(full):
        st.image(full, caption=caption, use_column_width=(width is None))
    else:
        st.markdown(
            f"<div style='background:#FEF2F2; border:1px solid #FECACA; border-radius:8px; "
            f"padding:12px 16px; font-size:13px; color:#991B1B;'>"
            f"⚠️ Chart not found: <code>{path}</code> — run the pipeline scripts to generate outputs.</div>",
            unsafe_allow_html=True
        )

def hero(eyebrow, title, subtitle):
    """Page hero header with eyebrow, title and subtitle."""
    st.markdown(f"""
    <div class="page-hero">
        <div class="page-hero-eye">{eyebrow}</div>
        <div class="page-hero-title">{title}</div>
        <div class="page-hero-sub">{subtitle}</div>
    </div>""", unsafe_allow_html=True)

def section(title):
    """Lightweight section label with horizontal rule — replaces heavy navy bars."""
    st.markdown(f'<div class="section-label">{title}</div>', unsafe_allow_html=True)

def kpi(label, value, sub=""):
    """KPI metric card with gold top border."""
    return f"""<div class="kpi-card">
        <div class="label">{label}</div>
        <div class="value">{value}</div>
        <div class="sub">{sub}</div>
    </div>"""

def card(html):
    """Generic white content card."""
    st.markdown(f'<div class="card">{html}</div>', unsafe_allow_html=True)

def finding(tag, winner, metric, body):
    """Result card with gradient top accent, winner name, metric pill, and body text."""
    st.markdown(f"""<div class="finding-box">
        <div class="ftitle">{tag}</div>
        <div class="fwinner">{winner}</div>
        <div class="fmetric">{metric}</div>
        <div class="fbody">{body}</div>
    </div>""", unsafe_allow_html=True)

def implication(title, body):
    """Amber note/implication box."""
    st.markdown(f"""<div class="implication">
        <div class="ititle">{title}</div>
        <div class="ibody">{body}</div>
    </div>""", unsafe_allow_html=True)

def insight_card(tag, title, body, stat):
    """Dark navy insight highlight card."""
    st.markdown(f"""<div class="insight-card">
        <div class="ic-tag">{tag}</div>
        <div class="ic-title">{title}</div>
        <div class="ic-body">{body}</div>
        <div class="ic-stat">{stat}</div>
    </div>""", unsafe_allow_html=True)

def class_card(icon, title, body, stat):
    """Light card for Obesity / Activity / Diet behavioral class."""
    st.markdown(f"""<div class="class-card">
        <div class="cc-icon">{icon}</div>
        <div class="cc-title">{title}</div>
        <div class="cc-body">{body}</div>
        <div class="cc-stat">{stat}</div>
    </div>""", unsafe_allow_html=True)

# ── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    # Brand header
    st.markdown(f"""
    <div style='padding:20px 4px 16px 4px;'>
        <div style='font-size:11px; font-weight:700; color:{GOLD}; text-transform:uppercase;
                    letter-spacing:1.4px; margin-bottom:6px;'>CDC BRFSS · 2011–2024</div>
        <div style='font-size:18px; font-weight:800; color:#FFFFFF; line-height:1.25;'>
            Statistical Learning<br>Analysis
        </div>
        <div style='font-size:11px; color:rgba(255,255,255,0.45); margin-top:6px;'>
            Ecological · Population-Level
        </div>
    </div>
    <div style='height:1px; background:rgba(255,255,255,0.1); margin:0 0 18px 0;'></div>
    """, unsafe_allow_html=True)

    page = st.selectbox("Navigate", [
        "🏠  Overview",
        "📄  Executive Summary",
        "🧹  Data Preparation & Constraints",
        "🔍  Exploratory Data Analysis",
        "📈  Regression Models",
        "🎯  Classification",
        "🔵  Clustering & PCA",
        "📋  Findings & Conclusions",
    ])

    # Key stats chips
    st.markdown(f"""
    <div style='height:1px; background:rgba(255,255,255,0.1); margin:18px 0 14px 0;'></div>
    <div style='font-size:10px; font-weight:700; color:{GOLD}; text-transform:uppercase;
                letter-spacing:1px; margin-bottom:10px;'>Key Numbers</div>
    <div style='display:flex; flex-wrap:wrap; gap:6px;'>
        <span style='background:rgba(255,255,255,0.1); border:1px solid rgba(255,255,255,0.15);
                     border-radius:20px; padding:4px 10px; font-size:11px; color:#fff;'>391 obs.</span>
        <span style='background:rgba(255,255,255,0.1); border:1px solid rgba(255,255,255,0.15);
                     border-radius:20px; padding:4px 10px; font-size:11px; color:#fff;'>14 years</span>
        <span style='background:rgba(255,255,255,0.1); border:1px solid rgba(255,255,255,0.15);
                     border-radius:20px; padding:4px 10px; font-size:11px; color:#fff;'>R²=0.237</span>
        <span style='background:rgba(255,255,255,0.1); border:1px solid rgba(255,255,255,0.15);
                     border-radius:20px; padding:4px 10px; font-size:11px; color:#fff;'>70.3% CV</span>
        <span style='background:rgba(255,255,255,0.1); border:1px solid rgba(255,255,255,0.15);
                     border-radius:20px; padding:4px 10px; font-size:11px; color:#fff;'>k=4 clusters</span>
    </div>
    <div style='height:1px; background:rgba(255,255,255,0.1); margin:18px 0 14px 0;'></div>
    <div style='font-size:10px; font-weight:700; color:{GOLD}; text-transform:uppercase;
                letter-spacing:1px; margin-bottom:8px;'>Methods</div>
    <div style='font-size:12px; color:rgba(255,255,255,0.65); line-height:2;'>
        OLS · Ridge Regression<br>
        Logistic · Decision Tree<br>
        Random Forest · SVM<br>
        K-Means · PCA
    </div>
    <div style='height:1px; background:rgba(255,255,255,0.1); margin:18px 0 14px 0;'></div>
    <div style='font-size:11px; color:rgba(255,255,255,0.5); line-height:1.8;'>
        <span style='color:#fff; font-weight:600;'>Chris Rodrigues</span><br>
        MAS Data Science<br>
        Illinois Institute of Technology
    </div>
    """, unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE: OVERVIEW
# ════════════════════════════════════════════════════════════════════════════
if "Overview" in page:
    hero(
        "CDC BRFSS · 2011–2024 · Ecological Analysis",
        "BRFSS Statistical Learning Analysis",
        "Can national physical activity levels and dietary habits predict obesity rates across U.S. demographic groups from 2011 to 2024?"
    )

    c1,c2,c3,c4,c5,c6 = st.columns(6)
    with c1: st.markdown(kpi("Raw Rows", "110,880", "before cleaning"), unsafe_allow_html=True)
    with c2: st.markdown(kpi("Years", "2011–2024", "14 annual cycles"), unsafe_allow_html=True)
    with c3: st.markdown(kpi("Locations", "55", "states & territories"), unsafe_allow_html=True)
    with c4: st.markdown(kpi("Best Reg. R²", "0.237", "Ridge combined"), unsafe_allow_html=True)
    with c5: st.markdown(kpi("Best CV Acc.", "70.3%", "Random Forest, Dataset B"), unsafe_allow_html=True)
    with c6: st.markdown(kpi("Clusters", "k = 4", "silhouette = 0.43"), unsafe_allow_html=True)

    section("Study Design")
    col1, col2 = st.columns([3, 2])
    with col1:
        card(f"""
            <b style='color:{NAVY};'>Unit of analysis:</b> Every value is a population-level
            percentage — the proportion of adults in a given state, year, and demographic group
            who meet a criterion. This is an <b>ecological analysis</b>, not individual-level data.<br><br>
            <b style='color:{NAVY};'>Three behavioral classes:</b><br>
            &nbsp;&nbsp;• <b>Obesity</b> — % adults with obesity (2011–2024)<br>
            &nbsp;&nbsp;• <b>Inactive</b> — % adults with no leisure-time physical activity (2011–2024)<br>
            &nbsp;&nbsp;• <b>PoorDiet</b> — avg of % eating fruit &lt;1/day and veg &lt;1/day (2017, 2019, 2021 only)<br><br>
            <b style='color:{NAVY};'>Stratification:</b> Each location × year is broken down by
            Age, Sex, Income, Education, Race/Ethnicity, and Total — giving 391 national
            observations for activity and 84 for diet (limited diet survey years).
        """)
    with col2:
        section("Pipeline")
        card(f"""
            <div style='font-size:13px; line-height:2.1;'>
            <b style='color:{GOLD};'>1.</b> brfss_clean.py &nbsp;→&nbsp; ETL pipeline<br>
            <b style='color:{GOLD};'>2.</b> brfss_eda.py &nbsp;&nbsp;&nbsp;→&nbsp; EDA & correlations<br>
            <b style='color:{GOLD};'>3.</b> brfss_model.py &nbsp;→&nbsp; OLS + Ridge regression<br>
            <b style='color:{GOLD};'>4.</b> brfss_classify.py → Classification<br>
            <b style='color:{GOLD};'>5.</b> brfss_cluster.py → K-Means + PCA<br>
            <b style='color:{GOLD};'>6.</b> app.py &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;→&nbsp; This dashboard
            </div>
        """)

    st.markdown("<br>", unsafe_allow_html=True)
    section("Model Results Summary")
    results = pd.DataFrame({
        "Model": ["OLS: Obesity ~ Inactive", "OLS: Obesity ~ PoorDiet",
                  "Ridge: Obesity ~ Inactive + PoorDiet",
                  "Classification (Dataset A) — Best CV",
                  "Classification (Dataset B) — Best CV",
                  "K-Means Clustering"],
        "n": [391, 84, 84, 391, 84, 391],
        "Result": ["R²=0.213", "R²=0.170", "R²=0.237, CV R²=0.161",
                   "Random Forest 67.8% CV accuracy",
                   "Random Forest 70.3% CV accuracy",
                   "k=4, silhouette=0.43"],
        "Key Finding": [
            "β=0.445, p<0.001 — inactivity significantly predicts obesity",
            "β=0.658, p<0.001 — diet has larger per-unit effect",
            "Combined model outperforms single-predictor OLS",
            "Inactive + StratCat predicts high/low obesity risk",
            "Adding PoorDiet improves classification performance",
            "4 clusters incl. Young Adult Paradox"
        ]
    })
    st.dataframe(results, use_container_width=True, hide_index=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE: EXECUTIVE SUMMARY
# ════════════════════════════════════════════════════════════════════════════
elif "Executive Summary" in page:
    hero(
        "Research Overview · Six Research Questions",
        "Executive Summary",
        "A comprehensive statistical learning pipeline examining how behavioral risk factors predict population-level obesity across U.S. demographic groups."
    )

    # ── Top KPIs ──────────────────────────────────────────────────────────
    c1,c2,c3,c4,c5,c6 = st.columns(6)
    with c1: st.markdown(kpi("Dataset", "CDC BRFSS", "2011–2024 · 14 years"), unsafe_allow_html=True)
    with c2: st.markdown(kpi("Analysis", "Ecological", "Population-level %"), unsafe_allow_html=True)
    with c3: st.markdown(kpi("Observations", "391 / 84", "Activity / Diet rows"), unsafe_allow_html=True)
    with c4: st.markdown(kpi("Best Reg. R²", "0.237", "Ridge, combined model"), unsafe_allow_html=True)
    with c5: st.markdown(kpi("Best CV Acc.", "70.3%", "Random Forest · Diet"), unsafe_allow_html=True)
    with c6: st.markdown(kpi("Clusters", "k = 4", "Silhouette = 0.43"), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Study Overview ────────────────────────────────────────────────────
    section("Study Overview")
    card("""
        <p style='margin:0 0 14px 0;'>
            This report presents a comprehensive statistical learning analysis of the
            <b>CDC Behavioral Risk Factor Surveillance System (BRFSS)</b> spanning 2011–2024.
            Using a five-stage pipeline of supervised and unsupervised machine learning methods,
            we investigate whether national <b>physical activity levels</b> and <b>dietary habits</b>
            can predict <b>obesity rates</b> across U.S. demographic groups.
        </p>
        <p style='margin:0 0 14px 0;'>
            A critical structural feature of this project is its <b>ecological framing</b>: every data
            point is a population-level percentage — the share of adults in a given state, year,
            and demographic group who meet a criterion — not an individual's personal record.
            This produces 391 observations for the activity dataset (Inactive %) and 84 observations
            for the diet dataset (PoorDiet %), reflecting the limited years in which diet survey
            questions were fielded (2017, 2019, 2021). All findings must be interpreted with this
            ecological fallacy caveat in mind: associations observed at the population level do not
            necessarily hold for individuals.
        </p>
        <p style='margin:0;'>
            The analysis is organized around <b>six structured research questions</b> covering
            regression, classification, regularization (Ridge), cross-validation, and clustering,
            forming an end-to-end machine learning workflow applicable to public health, insurance,
            and policy domains.
        </p>
    """)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Six Research Questions ────────────────────────────────────────────
    section("Research Questions & Key Findings")
    rq_data = [
        ("RQ1", "📈", "Regression: Inactivity → Obesity",
         "OLS · Model 1",
         "Does the percentage of physically inactive adults predict obesity rates across demographic groups?",
         "Yes — inactivity is a statistically significant predictor. β = 0.445 (p < 0.001), R² = 0.213. "
         "For every 1 pp increase in inactivity, obesity rises by ~0.45 pp at the population level. "
         "Moderate fit, reflecting real-world ecological complexity."),
        ("RQ2", "🥗", "Regression: Diet → Obesity",
         "OLS · Model 2",
         "Does poor dietary behavior (low fruit & vegetable consumption) predict obesity rates?",
         "Yes — PoorDiet has a larger per-unit effect than inactivity. β = 0.658 (p < 0.001), R² = 0.170. "
         "However, diet data is limited to 3 survey years (2017, 2019, 2021), reducing power to n = 84."),
        ("RQ3", "🔗", "Regression: Combined Model",
         "Ridge · Model 3",
         "Does combining inactivity and diet improve prediction over either alone?",
         "Yes — the Ridge-regularized combined model achieves R² = 0.237 (CV R² = 0.161). "
         "Ridge was chosen over OLS because the two predictors are collinear (VIF = 28.15), "
         "causing OLS coefficient instability. Ridge shrinkage resolves this."),
        ("RQ4", "🎯", "Classification: Activity Dataset",
         "5-Fold CV · Dataset A (n=391)",
         "Can demographic strata and inactivity rates be used to classify high vs. low obesity risk?",
         "Random Forest achieves the best cross-validated accuracy: 67.8% (5-fold stratified CV). "
         "Features: Inactive % + demographic stratification category. "
         "Decision Tree and Logistic Regression also competitive; SVM lowest."),
        ("RQ5", "🏆", "Classification: Diet Dataset",
         "5-Fold CV · Dataset B (n=84)",
         "Does adding poor diet as a feature improve classification of obesity risk groups?",
         "Yes — adding PoorDiet lifts Random Forest CV accuracy to 70.3% (vs. 67.8% without). "
         "This improvement is meaningful given the smaller sample (n=84) and confirms "
         "diet's incremental predictive value beyond activity alone."),
        ("RQ6", "🔵", "Clustering & PCA",
         "K-Means · k=4 · PCA",
         "Do natural behavioral clusters exist among U.S. demographic groups in the BRFSS data?",
         "K-Means (k=4) reveals four clinically meaningful population subgroups with silhouette = 0.43: "
         "(1) Low Obesity/Active, (2) High Obesity/Sedentary, (3) Moderate Risk, and (4) a "
         "Young Adult Paradox cluster — low obesity despite high inactivity. "
         "PCA confirms clear cluster separation in 2D space."),
    ]

    for rq_id, icon, title, badge, question, rq_finding in rq_data:
        st.markdown(f"""
        <div class="rq-card">
            <div style='display:flex; align-items:center; gap:10px; margin-bottom:10px; flex-wrap:wrap;'>
                <span style='background:{NAVY}; color:#fff; font-size:10px; font-weight:700;
                             padding:3px 10px; border-radius:4px; letter-spacing:0.5px;'>{rq_id}</span>
                <span style='font-size:17px;'>{icon}</span>
                <span style='font-size:14px; font-weight:700; color:{TEXT};'>{title}</span>
                <span style='margin-left:auto; background:{BG}; color:{SLATE}; border:1px solid {BORDER};
                             font-size:11px; padding:3px 10px; border-radius:20px;'>{badge}</span>
            </div>
            <p style='font-size:13px; color:{MUTED}; margin:0 0 8px 0; font-style:italic; line-height:1.6;'>
                {question}
            </p>
            <p style='font-size:13.5px; color:{SLATE}; margin:0; line-height:1.75;'>
                ✅ {rq_finding}
            </p>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Methodology Summary ───────────────────────────────────────────────
    section("Methodology at a Glance")
    m1, m2, m3 = st.columns(3)
    method_style = f"background:{WHITE}; border-radius:10px; padding:18px 20px; " \
                   f"box-shadow:0 2px 8px rgba(13,43,94,0.07); font-size:13px; " \
                   f"color:#333; line-height:1.9; height:100%;"
    with m1:
        st.markdown(f"""
        <div style='{method_style}'>
            <div style='font-size:14px; font-weight:700; color:{NAVY}; margin-bottom:8px;'>
                📥 Data & ETL
            </div>
            Source: CDC BRFSS 2011–2024<br>
            Raw: 110,880 rows × 33 columns<br>
            Filter: Sample_Size ≥ 50<br>
            Kept: 7 core columns<br>
            Aggregation: National weighted %<br>
            PoorDiet = (LowFruit + LowVeg) / 2<br>
            Final: 391 rows (Activity), 84 (Diet)
        </div>
        """, unsafe_allow_html=True)
    with m2:
        st.markdown(f"""
        <div style='{method_style}'>
            <div style='font-size:14px; font-weight:700; color:{NAVY}; margin-bottom:8px;'>
                🤖 Models Applied
            </div>
            OLS Regression (Models 1 & 2)<br>
            Ridge Regression (Model 3, α tuned)<br>
            Logistic Regression<br>
            Decision Tree<br>
            Random Forest (best performer)<br>
            Support Vector Machine<br>
            K-Means Clustering + PCA
        </div>
        """, unsafe_allow_html=True)
    with m3:
        st.markdown(f"""
        <div style='{method_style}'>
            <div style='font-size:14px; font-weight:700; color:{NAVY}; margin-bottom:8px;'>
                ✅ Validation Strategy
            </div>
            Regression: OLS diagnostics,<br>
            &nbsp;&nbsp;VIF check, residual analysis<br>
            Ridge: α selected via CV<br>
            Classification: 5-fold<br>
            &nbsp;&nbsp;StratifiedKFold CV<br>
            Clustering: Elbow + silhouette<br>
            Ecological fallacy noted throughout
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Overall Conclusion ────────────────────────────────────────────────
    section("Overall Conclusion")
    st.markdown(f"""
    <div style='background:linear-gradient(135deg, {NAVY} 0%, #1a3d7a 100%);
                border-radius:10px; padding:24px 28px; color:#fff; line-height:1.85; font-size:14px;'>
        <p style='margin:0 0 12px 0;'>
            Physical inactivity and poor diet are <b>statistically significant ecological predictors</b>
            of population-level obesity rates in the United States. While regression R² values
            (0.17–0.24) reflect the inherent complexity of predicting aggregate health outcomes,
            classification models achieve meaningful accuracy (67–70% cross-validated), and
            clustering reveals four distinct behavioral phenotypes with real-world public health relevance.
        </p>
        <p style='margin:0;'>
            The <b>Young Adult Paradox</b> cluster — groups showing low obesity despite high inactivity —
            is the most policy-relevant finding, suggesting that age and metabolic factors may buffer
            the effects of sedentary behavior in younger populations, with risk likely emerging later
            in life. Together, these findings support targeted, demographically-aware public health
            interventions rather than one-size-fits-all approaches.
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown(f"""
    <div style='margin-top:12px; padding:12px 16px; background:#fff8e7;
                border-left:4px solid {GOLD}; border-radius:6px; font-size:13px; color:#555;'>
        ⚠️ <b>Ecological Fallacy Reminder:</b> All findings are population-level associations.
        These results describe group-level trends and <i>cannot</i> be used to infer risk for
        any individual person. Correlation at the ecological level does not imply the same
        relationship holds within individuals.
    </div>
    """, unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE: DATA PREPARATION & CONSTRAINTS
# ════════════════════════════════════════════════════════════════════════════
elif "Data Preparation" in page:
    hero(
        "ETL Pipeline · 4-Step Process",
        "Data Preparation & Constraints",
        "What the raw data looked like, what we kept, what we removed, and why — explained plainly."
    )

    section("What We Started With")
    c1, c2, c3, c4 = st.columns(4)
    with c1: st.markdown(kpi("Raw Rows", "110,880", "before any cleaning"), unsafe_allow_html=True)
    with c2: st.markdown(kpi("Raw Columns", "33", "most were redundant"), unsafe_allow_html=True)
    with c3: st.markdown(kpi("Kept Columns", "7", "genuinely useful ones"), unsafe_allow_html=True)
    with c4: st.markdown(kpi("Final Dataset", "391 rows", "national, activity only"), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Step 1
    section("Step 1 — Understanding the Raw Data")
    st.markdown(f"""
    <div style='background:{WHITE}; border-radius:10px; padding:22px;
                box-shadow:0 2px 8px rgba(13,43,94,0.08); font-size:14px;
                color:#333; line-height:1.8;'>
        The raw BRFSS file arrives with <b>110,880 rows and 33 columns</b> — but most of those
        columns are either duplicates, codes that repeat information already in plain text,
        or flags that only matter for rows we're going to remove anyway.<br><br>
        After inspecting all 33 columns, we found only <b>7 carry real, non-redundant information</b>:
        the survey year, the location, the topic class, the specific question, the percentage value,
        the sample size, and the demographic group. Everything else was dropped.
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    col1, col2 = st.columns(2)
    with col1:
        section("❌ Columns Removed (26 of 33)")
        removed = pd.DataFrame({
            "Column": ["YearEnd", "LocationAbbr", "Datasource", "Topic", "Data_Value_Unit",
                       "Data_Value_Type", "Data_Value_Alt", "Data_Value_Footnote",
                       "Low/High Confidence Limit", "GeoLocation",
                       "Age, Education, Sex, Income, Race/Ethnicity",
                       "ClassID, TopicID, QuestionID, LocationID, etc."],
            "Why Removed": [
                "Always equals YearStart — adds nothing",
                "Duplicate of the full location name",
                "Every row says 'BRFSS' — constant",
                "Duplicate of Class column",
                "Every row says '%' — constant",
                "Every row says 'Value' — constant",
                "Numeric copy of the percentage column",
                "Only present on rows we're removing anyway",
                "Reliability handled by sample size filter",
                "Not needed — we use location names",
                "Same info captured in the Stratification column",
                "Numeric codes duplicating text columns"
            ]
        })
        st.dataframe(removed, use_container_width=True, hide_index=True)

    with col2:
        section("✅ Columns Kept (7 of 33)")
        kept = pd.DataFrame({
            "Column": ["YearStart", "LocationDesc", "Class", "Question",
                       "Data_Value", "Sample_Size", "StratificationCategory1 + Stratification1"],
            "What It Means": [
                "The survey year (2011–2024)",
                "Which state or territory",
                "Obesity, Physical Activity, or Diet",
                "The specific survey question asked",
                "The percentage answer (e.g. 32.1% are obese)",
                "How many people were surveyed for that estimate",
                "The demographic group (e.g. Education → College graduate)"
            ]
        })
        st.dataframe(kept, use_container_width=True, hide_index=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # Step 2
    section("Step 2 — Removing Unreliable Estimates")
    card("""
        Some rows in the dataset are based on very few survey respondents — fewer than 50 people.
        A percentage calculated from 12 people is not a reliable population estimate.
        We removed all rows where <b>Sample Size &lt; 50</b>, keeping only estimates
        with enough respondents to be statistically meaningful.<br><br>
        This is a standard data quality filter — not an arbitrary choice.
        The confidence limits columns (which we also removed) existed specifically
        to flag these low-reliability rows.
    """)

    # Step 3
    section("Step 3 — The Three Separate Classes (A Critical Structural Constraint)")
    card("""
        This is the most important structural property of the dataset — and the one most likely
        to be misunderstood.<br><br>
        The BRFSS data contains <b>three separate topic classes</b>, each collected independently:
    """)

    c1, c2, c3 = st.columns(3)
    with c1:
        class_card("⚖️", "Obesity",
                   "% of adults classified with obesity<br>Available: 2011–2024, all demographics",
                   "391 national records")
    with c2:
        class_card("🏃", "Physical Activity",
                   "% of adults with no leisure-time physical activity<br>Available: 2011–2024",
                   "391 national records")
    with c3:
        class_card("🥦", "Diet",
                   "% eating fruit &lt;1/day + % eating veg &lt;1/day<br>Available: 2017, 2019, 2021 only",
                   "84 national records")

    st.markdown("""
    <div class="eco-warning">
        <b>⚠️ Important:</b> These three classes were surveyed <b>separately</b>, with potentially
        different respondents contributing to each estimate within the same state and year.
        We <b>cannot observe obesity, physical activity, and diet for the same individual</b>.
        We can only compare population-level averages for the same location, year, and demographic group.<br><br>
        This is why all findings in this study are <b>ecological</b> — they describe patterns
        across population groups, not individuals. A state with high inactivity and high obesity
        does not mean the inactive people <em>are</em> the obese people.
    </div>
    """, unsafe_allow_html=True)

    # Step 4
    section("Step 4 — Reshaping and Aggregating to National Level")
    card("""
        <b>Reshaping (Pivot):</b> The raw data has one row per question — so the same
        state/year/group would have multiple rows for different questions. We reshaped it so
        each combination of year + location + demographic group gets <b>one row</b>,
        with each question as its own column. This is called a pivot.<br><br>
        <b>National aggregation:</b> Rather than analyse all 55 states separately,
        we aggregated to a <b>national weighted average</b> per year and demographic group.
        States with more survey respondents count more in the average — this is called
        weighting by sample size. This gives us one clean national estimate per
        year × demographic group combination.<br><br>
        <b>PoorDiet score:</b> We combined the two diet questions (% eating fruit &lt;1/day
        and % eating vegetables &lt;1/day) into a single <b>PoorDiet score</b> by averaging
        them — a higher score means worse diet quality.
    """)

    # Final dataset summary
    section("What We Ended Up With")
    datasets = pd.DataFrame({
        "Dataset": [
            "Obesity (national)",
            "Activity (national)",
            "Diet (national)",
            "Modeling dataset — Regression M1 & Classification A",
            "Modeling dataset — Regression M2/M3 & Classification B",
            "Clustering dataset"
        ],
        "Rows": [391, 391, 84, 391, 84, 391],
        "Years": ["2011–2024", "2011–2024", "2017, 2019, 2021", "2011–2024", "2017, 2019, 2021", "2011–2024"],
        "Key Variables": [
            "Year, StratGroup, Obesity %",
            "Year, StratGroup, Inactive %",
            "Year, StratGroup, LowFruit %, LowVeg %, PoorDiet %",
            "Obesity + Inactive (merged on Year × StratGroup)",
            "Obesity + Inactive + PoorDiet (merged on Year × StratGroup)",
            "Obesity + Inactive + PoorDiet (imputed where missing)"
        ]
    })
    st.dataframe(datasets, use_container_width=True, hide_index=True)

    st.markdown(f"""
    <div class="finding-box" style="margin-top:16px;">
        <div class="ftitle">💡 Why Diet Has So Few Rows</div>
        <div class="fwinner">84 rows vs 391 — not a mistake</div>
        <div class="fbody">
            Fruit and vegetable consumption data was only collected at the Overall
            (non-demographic) stratification level in 2017, 2019, and 2021.
            This is a CDC data collection decision — not something we could fix.
            It means any finding involving diet is based on 3 years of data only,
            which is why we treat diet results more cautiously than activity results throughout the analysis.
        </div>
    </div>
    """, unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════════════════
# PAGE: EDA
# ════════════════════════════════════════════════════════════════════════════
elif "Exploratory" in page:
    hero(
        "Distributions · Trends · Correlations",
        "Exploratory Data Analysis",
        "Distributions, trends across 14 years, demographic breakdowns, and cross-indicator correlations — before any modeling."
    )

    tab1, tab2, tab3, tab4 = st.tabs(["🏋️ Obesity", "🚶 Physical Activity", "🥦 Diet", "🔗 Combined"])

    with tab1:
        section("Obesity — Distribution & National Trend")
        c1, c2 = st.columns(2)
        with c1: img("eda_outputs/obesity_q1_distribution.png", "Distribution of obesity rates across all strata")
        with c2: img("eda_outputs/obesity_q2_trend.png", "National obesity trend 2011–2024")

        section("Obesity by Demographic Group")
        c1, c2, c3 = st.columns(3)
        with c1: img("eda_outputs/obesity_q3_age_(years).png", "By Age")
        with c2: img("eda_outputs/obesity_q3_education.png", "By Education")
        with c3: img("eda_outputs/obesity_q3_income.png", "By Income")
        c4, c5 = st.columns(2)
        with c4: img("eda_outputs/obesity_q3_race_ethnicity.png", "By Race/Ethnicity")
        with c5: img("eda_outputs/obesity_q3_sex.png", "By Sex")

        finding(
            "Obesity EDA Finding",
            "Obesity rose +5.8 pp nationally (2011–2024)",
            "Correlation with Year: r = +0.98",
            "The national obesity trend is nearly perfectly linear with time — a stronger "
            "statistical relationship than with any behavioral indicator. Education and income "
            "show the steepest demographic gradients: college graduates have substantially lower "
            "obesity than adults without a high school diploma. This socioeconomic gap widened over the study period."
        )

        img("eda_outputs/obesity_q4_variation_by_strat.png", "Obesity variation by stratification category")

    with tab2:
        section("Physical Activity — Distribution & National Trend")
        c1, c2 = st.columns(2)
        with c1: img("eda_outputs/activity_q1_distribution.png", "Distribution of inactivity rates")
        with c2: img("eda_outputs/activity_q2_trend.png", "National inactivity trend 2011–2024")

        section("Inactivity by Demographic Group")
        c1, c2, c3 = st.columns(3)
        with c1: img("eda_outputs/activity_q3_age_(years).png", "By Age")
        with c2: img("eda_outputs/activity_q3_education.png", "By Education")
        with c3: img("eda_outputs/activity_q3_income.png", "By Income")
        c4, c5 = st.columns(2)
        with c4: img("eda_outputs/activity_q3_race_ethnicity.png", "By Race/Ethnicity")
        with c5: img("eda_outputs/activity_q3_sex.png", "By Sex")

        finding(
            "Activity EDA Finding",
            "Inactivity showed NO significant trend 2011–2024",
            "Correlation with Year: r = −0.39, p = 0.17",
            "While obesity rose steadily, physical inactivity remained flat — the two indicators "
            "diverged over the study period. This is a critical finding: the rising obesity trend "
            "cannot be explained by worsening physical activity rates alone. Education shows the "
            "strongest inactivity-obesity correlation (r = +0.78)."
        )

        img("eda_outputs/activity_q4_vs_obesity.png", "Inactivity vs Obesity scatter by demographic group")

    with tab3:
        section("Diet — Fruit & Vegetable Consumption")
        st.info("⚠️ Diet data available for 2017, 2019, and 2021 only (Overall stratification). All diet findings are based on 84 observations across 3 years.")
        img("eda_outputs/diet_q1_rates.png", "Low fruit and low vegetable consumption rates")

        section("Diet by Demographic Group")
        c1, c2, c3 = st.columns(3)
        with c1: img("eda_outputs/diet_q2_age_(years).png", "By Age")
        with c2: img("eda_outputs/diet_q2_education.png", "By Education")
        with c3: img("eda_outputs/diet_q2_income.png", "By Income")
        c4, c5 = st.columns(2)
        with c4: img("eda_outputs/diet_q2_race_ethnicity.png", "By Race/Ethnicity")
        with c5: img("eda_outputs/diet_q2_sex.png", "By Sex")

        img("eda_outputs/diet_q3_vs_obesity.png", "PoorDiet vs Obesity scatter")

        finding(
            "Diet EDA Finding",
            "PoorDiet has a larger per-unit effect than Inactivity",
            "β = 0.658 vs β = 0.445 (regression)",
            "Despite having only 3 years of data, diet quality shows a stronger per-unit "
            "relationship with obesity than physical activity. Low-income and less-educated "
            "groups show both higher inactivity AND poorer diet — compounding risk. "
            "The limited diet data (84 rows) means these findings should be interpreted cautiously."
        )

    with tab4:
        section("Cross-Indicator Correlations")
        img("eda_outputs/combined_q1_correlation.png", "Correlation matrix: Obesity, Inactive, PoorDiet")
        c1, c2 = st.columns(2)
        with c1: img("eda_outputs/combined_q2_vif.png", "Variance Inflation Factor — multicollinearity check")
        with c2: img("eda_outputs/combined_scatter_matrix.png", "Scatter matrix across all three indicators")

        finding(
            "Multicollinearity Finding",
            "VIF = 28.15 between Inactive and PoorDiet",
            "Justifies Ridge regression for the combined model",
            "Inactive and PoorDiet are highly correlated with each other (VIF=28.15), meaning "
            "OLS coefficient estimates would be unreliable in a combined model. This is why "
            "Ridge regression was selected for Model 3 — L2 regularization stabilizes "
            "coefficient estimates under multicollinearity."
        )

# ════════════════════════════════════════════════════════════════════════════
# PAGE: REGRESSION
# ════════════════════════════════════════════════════════════════════════════
elif "Regression" in page:
    hero(
        "OLS · Ridge · VIF-Corrected · 3 Models",
        "Regression Models",
        "Three models predicting population-level obesity rates from physical activity and dietary behavior."
    )

    tab1, tab2, tab3 = st.tabs(["Model 1 — Inactive", "Model 2 — PoorDiet", "Model 3 — Ridge Combined"])

    with tab1:
        section("Model 1: Obesity ~ Physical Inactivity (OLS)")
        st.markdown("**n = 391 &nbsp;|&nbsp; All stratification groups &nbsp;|&nbsp; 2011–2024**")
        col1, col2 = st.columns([3, 1])
        with col1:
            img("model_outputs/model1_inactive.png", "Obesity vs Inactivity with OLS fit line")
        with col2:
            st.markdown(kpi("R²", "0.213", ""), unsafe_allow_html=True)
            st.markdown(kpi("β (Inactive)", "0.445", "p < 0.001 ***"), unsafe_allow_html=True)
            st.markdown(kpi("n", "391", "all strata, 14 years"), unsafe_allow_html=True)
        img("model_outputs/residuals_model_1_obesitybyinactive.png", "Residual diagnostics — Fitted vs Residuals and Q-Q Plot")
        finding(
            "Model 1 Finding",
            "Inactivity significantly predicts obesity",
            "β = 0.445 · R² = 0.213 · p < 0.001 · n = 391",
            "For every 1 percentage point increase in inactivity, obesity rises by 0.445 points. "
            "The relationship is statistically robust across all demographic groups and 14 years. "
            "However, inactivity alone explains only 21.3% of obesity variance — the majority of "
            "variation is driven by factors outside this model. Education groups show the strongest "
            "inactivity-obesity correlation (r = +0.78)."
        )
        implication("⚠️ Ecological Caution",
            "This is a population-level correlation — it does not mean inactive individuals are "
            "more likely to be obese. The ecological fallacy means group-level findings cannot "
            "be applied to individuals without individual-level confirmation.")

    with tab2:
        section("Model 2: Obesity ~ PoorDiet (OLS)")
        st.markdown("**n = 84 &nbsp;|&nbsp; All stratification groups &nbsp;|&nbsp; 2017, 2019, 2021 only**")
        col1, col2 = st.columns([3, 1])
        with col1:
            img("model_outputs/model2_diet.png", "Obesity vs PoorDiet with OLS fit line")
        with col2:
            st.markdown(kpi("R²", "0.170", ""), unsafe_allow_html=True)
            st.markdown(kpi("β (PoorDiet)", "0.658", "p < 0.001 ***"), unsafe_allow_html=True)
            st.markdown(kpi("n", "84", "3 diet years only"), unsafe_allow_html=True)
        img("model_outputs/residuals_model_2_obesitybypoordiet.png", "Residual diagnostics")
        finding(
            "Model 2 Finding",
            "PoorDiet has a larger per-unit effect than Inactivity",
            "β = 0.658 · R² = 0.170 · p < 0.001 · n = 84",
            "Each 1 point worsening in PoorDiet score is associated with a 0.658 point rise in "
            "obesity — a larger coefficient than inactivity (0.445). Despite having only 84 rows "
            "across 3 years, the relationship is statistically significant. The lower R² (0.170 vs "
            "0.213) compared to Model 1 is partly attributable to the smaller, less diverse sample."
        )

    with tab3:
        section("Model 3: Obesity ~ Inactive + PoorDiet (Ridge Regression)")
        st.markdown("**n = 84 &nbsp;|&nbsp; Ridge used due to VIF = 28.15 between predictors &nbsp;|&nbsp; α selected via 5-fold CV**")
        col1, col2 = st.columns(2)
        with col1:
            img("model_outputs/model3_ridge_coefficients.png", "Standardized Ridge coefficients")
        with col2:
            img("model_outputs/model3_predicted_vs_actual.png", "Predicted vs Actual obesity rates")
        c1,c2,c3 = st.columns(3)
        with c1: st.markdown(kpi("R² (train)", "0.237", "Combined model"), unsafe_allow_html=True)
        with c2: st.markdown(kpi("CV R²", "0.161", "5-fold cross-validated"), unsafe_allow_html=True)
        with c3: st.markdown(kpi("VIF", "28.15", "Justifies Ridge over OLS"), unsafe_allow_html=True)
        finding(
            "Model 3 Finding",
            "Ridge combined model achieves R² = 0.237",
            "Train R² = 0.237 · CV R² = 0.161 · n = 84",
            "The combined model outperforms both single-predictor models. PoorDiet receives "
            "a higher standardized coefficient than Inactive under Ridge — consistent with its "
            "larger raw β. The gap between train R² (0.237) and CV R² (0.161) reflects the "
            "limited sample size (84 rows). Together, both behavioral indicators explain only "
            "~24% of obesity variation — the remaining 76% is driven by unmeasured factors."
        )
        implication("💡 Why Ridge?",
            "OLS is unreliable when predictors are highly correlated (VIF=28.15). "
            "Ridge regression adds an L2 penalty that stabilizes coefficient estimates "
            "without zeroing out features — appropriate here since both Inactive and "
            "PoorDiet carry genuine signal.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE: CLASSIFICATION
# ════════════════════════════════════════════════════════════════════════════
elif "Classification" in page:
    hero(
        "Random Forest · Logistic · SVM · 5-Fold CV",
        "Classification",
        "Predicting high vs. low obesity risk groups across two datasets using supervised learning with stratified cross-validation."
    )

    tab1, tab2 = st.tabs(["Dataset A — Inactive + StratCat", "Dataset B — Inactive + PoorDiet + StratCat"])

    for tab, prefix, n_rows, label in [
        (tab1, "Dataset_A_Inactive_and_StratCat1", "391", "Dataset A: Inactive + StratificationCategory1"),
        (tab2, "Dataset_B_Inactive_and_PoorDiet_and_StratCat1", "84", "Dataset B: Inactive + PoorDiet + StratificationCategory1"),
    ]:
        with tab:
            section(f"Cross-Validation Results — {label}")
            results_file = f"classify_outputs/{prefix}_results.csv"
            if os.path.exists(os.path.join(BASE, results_file)):
                df = pd.read_csv(os.path.join(BASE, results_file))
                df_show = df[["Classifier","CV_Accuracy","CV_Acc_Std","CV_F1","CV_AUC"]].copy()
                df_show.columns = ["Classifier","CV Accuracy","CV Acc Std","CV F1","CV AUC"]
                df_show["CV Accuracy"] = (df_show["CV Accuracy"]*100).round(1).astype(str) + "%"
                df_show["CV Acc Std"] = ("±" + (df_show["CV Acc Std"]*100).round(1).astype(str) + "%")
                df_show["CV F1"] = df_show["CV F1"].round(3)
                df_show["CV AUC"] = df_show["CV AUC"].round(3)
                st.dataframe(df_show, use_container_width=True, hide_index=True)

            col1, col2 = st.columns(2)
            with col1:
                img(f"classify_outputs/{prefix}_cv_comparison.png", "CV accuracy comparison across classifiers")
                img(f"classify_outputs/{prefix}_roc_curves.png", "ROC curves")
            with col2:
                img(f"classify_outputs/{prefix}_confusion_matrices.png", "Confusion matrices")
                img(f"classify_outputs/{prefix}_feature_importance.png", "Random Forest feature importance")

            img(f"classify_outputs/{prefix}_decision_tree.png", "Decision Tree structure")

    finding(
        "Classification Finding",
        "Dataset B (with PoorDiet) outperforms Dataset A",
        "Dataset A best CV: Random Forest 67.8% · Dataset B best CV: Random Forest 70.3%",
        "Adding PoorDiet to the feature set improves all classifiers — confirming diet quality "
        "adds independent predictive signal beyond inactivity alone. Across both datasets, "
        "classifiers achieve 65–70% CV accuracy, which is meaningful but modest — consistent "
        "with the regression finding that behavioral indicators explain only ~24% of obesity "
        "variation. Random Forest is the top performer in both datasets."
    )
    implication("⚠️ Note on Random Forest Train Accuracy",
        "Random Forest achieves 100% training accuracy in both datasets — this is expected "
        "overfitting from an unconstrained ensemble on small samples. CV accuracy (67–70%) "
        "is the correct measure of generalizability.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE: CLUSTERING
# ════════════════════════════════════════════════════════════════════════════
elif "Clustering" in page:
    hero(
        "K-Means · PCA · Silhouette = 0.43 · k = 4",
        "Clustering & PCA",
        "Unsupervised discovery of behavioral phenotypes — including the Young Adult Paradox — across U.S. demographic groups."
    )

    section("Optimal K Selection")
    img("cluster_outputs/cluster_1_optimal_k.png", "Elbow method and silhouette scores — k=4 selected")

    section("PCA Cluster Visualization")
    img("cluster_outputs/cluster_2_pca.png", "Clusters projected onto 2 principal components")

    section("Cluster Profiles")
    col1, col2 = st.columns([2, 1])
    with col1:
        img("cluster_outputs/cluster_3_profiles.png", "Mean feature values per cluster")
    with col2:
        if os.path.exists(os.path.join(BASE, "cluster_outputs/cluster_profiles.csv")):
            df = pd.read_csv(os.path.join(BASE, "cluster_outputs/cluster_profiles.csv"))
            df.columns = ["Cluster", "Obesity %", "Inactive %", "PoorDiet %"]
            df["Cluster"] = df["Cluster"].map({
                0: "🔴 High Risk",
                1: "🟢 Low Risk",
                2: "🟡 Moderate",
                3: "🔵 Young Adult Paradox"
            })
            st.dataframe(df, use_container_width=True, hide_index=True)
            st.markdown(f"""
            <div class="kpi-card" style="margin-top:10px;">
                <div class="label">Silhouette Score</div>
                <div class="value">0.43</div>
                <div class="sub">Moderate — clusters are real but gradual</div>
            </div>""", unsafe_allow_html=True)

    section("Cluster Composition by Demographic Group")
    col1, col2 = st.columns(2)
    with col1:
        img("cluster_outputs/cluster_4_crosstab.png", "Which demographic groups fall in each cluster?")
    with col2:
        img("cluster_outputs/cluster_5_composition.png", "Cluster composition breakdown")

    finding(
        "Clustering Finding",
        "4 Behavioral Phenotypes — Including the Young Adult Paradox",
        "k=4 · Silhouette = 0.43 · Clusters cut across demographic boundaries",
        "The Young Adult Paradox cluster (Cluster 3) has low obesity (14.9%) despite high PoorDiet "
        "(31.2%) and moderate inactivity (19%). The unsupervised algorithm independently confirmed "
        "what EDA first observed — young adults' metabolic profile buffers the impact of poor behavioral "
        "choices on weight. Education and income groups drive the extreme clusters (High Risk and Low Risk). "
        "No single demographic category falls entirely into one cluster — risk profiles are not "
        "determined by demographics alone."
    )
    implication("💡 Why This Matters for Public Health",
        "A one-size-fits-all intervention strategy fails because it targets four distinct populations. "
        "The High Risk cluster needs structural support (food access, safe recreation spaces). "
        "The Young Adult Paradox cluster needs preventive dietary intervention NOW — before "
        "metabolic buffering diminishes with age. Cluster membership is socioeconomic, not demographic.")

# ════════════════════════════════════════════════════════════════════════════
# PAGE: FINDINGS & CONCLUSIONS
# ════════════════════════════════════════════════════════════════════════════
elif "Findings" in page:
    hero(
        "All Six Research Questions · Public Health Implications",
        "Findings & Conclusions",
        "Complete summary of results across regression, classification, and clustering — with real-world context."
    )

    c1,c2,c3,c4,c5 = st.columns(5)
    with c1: st.markdown(kpi("Best Reg. R²", "0.237", "Ridge — Inactive + PoorDiet"), unsafe_allow_html=True)
    with c2: st.markdown(kpi("Inactivity β", "0.445", "p < 0.001, n=391"), unsafe_allow_html=True)
    with c3: st.markdown(kpi("PoorDiet β", "0.658", "p < 0.001, n=84"), unsafe_allow_html=True)
    with c4: st.markdown(kpi("Best CV Acc.", "70.3%", "Random Forest, Dataset B"), unsafe_allow_html=True)
    with c5: st.markdown(kpi("Clusters", "k=4", "silhouette=0.43"), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    section("Key Findings Across All Analyses")

    col1, col2 = st.columns(2)
    with col1:
        insight_card("Regression — Model 1",
            "Inactivity significantly predicts obesity — but only partially",
            "β=0.445, R²=0.213, p<0.001, n=391. For every 1pp rise in inactivity, "
            "obesity rises 0.445pp. Robust across all demographic groups and 14 years. "
            "But inactivity explains only 21% of variance.",
            "R² = 0.213 · β = 0.445")
        insight_card("Regression — Model 3",
            "Combined behavioral model explains ~24% of obesity variation",
            "Ridge R²=0.237, CV R²=0.161. Both indicators together outperform either alone. "
            "The 76% unexplained variance points to unmeasured structural factors: "
            "food environment, ultra-processed foods, chronic stress, sleep.",
            "R² = 0.237 · CV R² = 0.161")
        insight_card("Clustering",
            "Young Adult Paradox: Low obesity despite poor diet",
            "K-Means (k=4) independently confirmed the EDA observation that young adults "
            "have poor dietary habits yet low obesity — metabolic buffering masks deteriorating "
            "behavioral trajectories that will emerge as they age.",
            "Cluster 3: Obesity 14.9% · PoorDiet 31.2%")

    with col2:
        insight_card("Temporal Trend",
            "Obesity rose +5.8pp while inactivity was flat",
            "Obesity: r=+0.98 with Year. Inactivity: r=−0.39, p=0.17 — not significant. "
            "The behavioral indicators explain cross-sectional demographic variation "
            "far better than the national temporal trend. Something else is driving rising obesity.",
            "Obesity r=+0.98 · Inactivity p=0.17 (n.s.)")
        insight_card("Classification",
            "Behavioral data achieves 65–70% accuracy — meaningful but modest",
            "Dataset B (with PoorDiet) outperforms Dataset A. Random Forest is the best "
            "classifier in both. 100% train accuracy reflects overfitting — CV accuracy "
            "is the honest measure. Consistent with R²≈0.24 from regression.",
            "Dataset B: 70.3% CV Accuracy")
        insight_card("Socioeconomic Gradient",
            "Education & income are the dominant structural factors",
            "Education shows the strongest inactivity-obesity correlation (r=+0.78). "
            "Education and income groups concentrate in the extreme clusters. "
            "Behavioral indicators are partly proxies for structural inequality — "
            "not just independent causes of obesity.",
            "Education r = +0.78 with obesity")

    st.markdown("<br>", unsafe_allow_html=True)
    section("Public Health Implications")

    col3, col4 = st.columns(2)
    with col3:
        implication("🏥 Behavioral interventions alone are insufficient",
            "Behavioral indicators explain only ~24% of obesity variation and inactivity is not "
            "rising while obesity is. Campaigns focused solely on individual behavior change will "
            "have limited impact. Structural factors — the food environment, built environment, "
            "income inequality — require policy attention alongside behavior change.")
        implication("🎯 Target socioeconomic gradients, not demographic labels",
            "The strongest risk signal comes from education and income, not from age, sex, or "
            "race/ethnicity per se. Interventions improving access to healthy food and safe "
            "recreational spaces for low-income communities address the root cause.")
    with col4:
        implication("👨‍🎓 Young adults need preventive attention NOW",
            "The Young Adult Paradox shows that current obesity rates in young adults mask "
            "deteriorating behavioral trajectories. Intervene before metabolic buffering "
            "diminishes with age — not after obesity is already observable.")
        implication("📊 Collect more diet data",
            "Diet shows a larger per-unit effect (β=0.658) than inactivity (β=0.445) but is "
            "only available for 3 years. Expanding annual dietary collection would substantially "
            "improve the evidence base and enable more robust modeling.")

    section("Study Limitations")
    lims = [
        ("Ecological Fallacy", "All analysis uses population averages — findings cannot be applied to individuals."),
        ("Diet data: 3 years only", "PoorDiet is available for 2017, 2019, 2021 only — 84 rows total. Limited statistical power."),
        ("Crude activity measure", "Inactive captures only absence of leisure-time activity — not occupational or transport activity."),
        ("PoorDiet imputation", "79% of PoorDiet values in clustering are imputed using stratification group means."),
        ("Self-reported data", "BMI from self-reported height/weight underestimates actual obesity prevalence."),
        ("Cross-sectional surveys", "Different individuals are surveyed each year — no individual longitudinal tracking."),
    ]
    c1, c2 = st.columns(2)
    for i, (title, desc) in enumerate(lims):
        col = c1 if i % 2 == 0 else c2
        with col:
            st.markdown(f"""
            <div style='background:{WHITE}; border-radius:8px; padding:12px 16px;
                        border-left:4px solid {RED if i < 2 else GOLD};
                        margin-bottom:10px; box-shadow:0 1px 4px rgba(0,0,0,0.05);'>
                <div style='font-size:12px; font-weight:800; color:{NAVY}; margin-bottom:3px;'>⚠️ {title}</div>
                <div style='font-size:13px; color:#555; line-height:1.5;'>{desc}</div>
            </div>""", unsafe_allow_html=True)

    st.markdown(f"""
    <div style='text-align:center; margin-top:30px; padding:16px;
                border-top:2px solid {GOLD}; color:#888; font-size:13px;'>
        Illinois Institute of Technology · MAS Data Science · Statistical Learning · Chris Rodrigues · 2025<br>
        <a href='https://github.com/chrisharry99us/brfss-statistical-learning'
           style='color:{GOLD}; text-decoration:none;'>
            📂 github.com/chrisharry99us/brfss-statistical-learning
        </a>
    </div>
    """, unsafe_allow_html=True)
